### ISSUE TITLE
Footprint updates from overlap analysis

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#120]
From the analysis in #100, the folks at Seattle have come up with new footprint fixes.

These are on their Sharepoint here, but I can never tell who will be able to access that, maybe only me:
https://seattlegov.sharepoint.com/:x:/r/sites/OSE-External/Shared%20Documents/Benchmarking/GreenInfo%20OSE%202024/Shape%20Review%20Fixes%2020240718.xlsx?d=w99b6598570244ea385f339e6fa2f0a87&csf=1&web=1&e=GiqCfK

So I also uploaded here:
https://docs.google.com/spreadsheets/d/113HDoy6WnkBAx-E7GCazrJRD9VWy4SQE/edit?gid=189376366#gid=189376366

It looks like about 104 building IDs identified for repair.

there's no huge rush on this, though completion in September would be ideal.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208265515320236)

**Comment by joseph-stout** [comment]
Shape fixes for Sept. 2024 (from sheet 20240718) are in. I saw a few other overlaps in nearby areas and can go back through and document the ID's for future review if necessary, otherwise the working file is ready to share.

P:\proj_p_s\Seattle Building Dashboard\2024_update\seattle_building_outlines_2024_update\seattle_building_outlines_2024_update

**Comment by danrademacher** [comment]
@tomay to update footprints using this data.

As a convenience, here's donwload https://www.dropbox.com/t/OH1TvEe5UEwbrC3n

**Comment by tomay** [comment]
This has been uploaded to `footprints_production`, and unless we note any issues, this is done
