### ISSUE TITLE
More footprint fixes, from gis size vs square foot ratio analysis

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/seattle-building-dashboard#123]
Mike finished the footprint review based on analysis in #102 

I saved his XLSX here:
https://docs.google.com/spreadsheets/d/1-3XT03AWcwHQU5NLgVtOA9Zkfb8Krunc?rtpof=true&usp=drive_fs

Looks like about 140 building IDs somehow implicated in fixes, with the sketches 

No huge rush on this, though sometime while I'm away would be nice (before 10/23). 

Just let @tomay know when updates or ready, or if you have questions that need to route back to Mike, he can facilitate that. Also fine if you wanted to join a client call to discuss anything. 

Notable: Mike said about half the buildings we highlighted with the ratio analysis were real errors, so he was pretty pleased with this method of detection.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1208472236752689)

**Comment by joseph-stout** [comment]
Excellent, I will start this next week. Glad the footprint ratio analysis was useful.

**Comment by joseph-stout** [comment]
@tomay I finished updating the footprint outlines for this round. I had a couple of questions that I highlighted in the "fixes" tab of the sheet in magenta (yellow indicates successful check/update). But overall I think I was able to interpret things pretty well. Let me know if there is anything else you need from me for this since Dan is out!

Here is the file path: P:\proj_p_s\Seattle Building Dashboard\2024_update\seattle_building_outlines_20241009

**Comment by joseph-stout** [comment]
Got clarification from Mike, he confirmed my interpretation for 565 and 27554 and I went back and removed the extra buildings from 26098. This should be ready to go now.

**Comment by tomay** [comment]
These have been updated on CARTO
