### ISSUE TITLE
Energy Use Trends - New Buildings Issue

### ISSUE THREAD

**Issue by seattle-benchmarking** [GreenInfo-Network/seattle-building-dashboard#24]
Can call this a nice to have.
There is a flaw in the original design of the ENERGY USE TRENDS graph. Buildings that are built after the first year of data (2015) show up as an error _Not enough data available_ even when they have data for every year they've existed. See id = [50254 ](https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2020?layer=energy_star_score&sort=energy_star_score&order=desc&lat=47.61001&lng=-122.33002&zoom=14&building=50254&report_active=true)as an example. This building has four years of site_eui_wn data but since it wasn't built or reporting data back to 2015 it throws an error.

![image](https://user-images.githubusercontent.com/58457382/146606610-c793bc2e-16e4-40eb-ade7-24a5234c8ad7.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201108652060192/1201534415013319)

**Comment by tomay** [comment]
I've applied a fix here that gets available years from a given buildings data instead of from `seattle.json`, but I'm leaving this open for additional testing. 

I do leave the original variable `avail_years` in place, in case it is used elsewhere. I only get `previousYear` from from the building data, right before passing to the `shift` template. Existing check to see that `selected_year !== previousYear` is left as is, as is the `no_year` flag

**Comment by seattle-benchmarking** [comment]
@tomay I did a bunch of testing on this. It seems to be performing quite well. The only odd behavior is sometimes the error message doesn't make sense. See id = [50662 ](https://greeninfo-network.github.io/seattle-building-dashboard/#seattle/2020?filters[0][field]=yearbuilt&filters[0][min]=2014&layer=yearbuilt&sort=yearbuilt&order=desc&lat=47.63442&lng=-122.30968&zoom=14&building=50662&report_active=true)as an example.

The building has 2020 data but shows this error:
![image](https://user-images.githubusercontent.com/58457382/147270607-22811cb4-5f05-4c52-a188-5d3471d6d26d.png)

And since 2020 is the first year of data for this building, selecting a different year isn't possible.

We might just need a different error message that is more generic.

**Comment by tomay** [comment]
There was already an error message for an invalid range of data. I extended this to include the case where there is only a single year of data

![image](https://user-images.githubusercontent.com/740512/147288701-6f64230a-dd72-4a03-9ac2-d507265a65cf.png)

**Comment by tomay** [comment]
Note: previously, they were trapping errors for buildings which were missing data at the beginning of the range (with an error like above - "No data available for the year 2015". 

This is no longer applicable, since we are taking whatever range of data is available. I haven't removed that completely, but instead worked around it

**Comment by seattle-benchmarking** [comment]
Thanks for the update. This looks good to me.
